# https://pre-commit.com
# https://github.com/pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace       # Removes trailing spaces
      - id: end-of-file-fixer         # Ensures a file ends with a newline
      - id: check-added-large-files   # Prevents committing large files
      - id: check-yaml                # Validates YAML syntax
      - id: check-json                # Validates JSON syntax
      - id: check-toml                # Validates TOML files
      - id: debug-statements          # Detects debug prints (e.g. `print`, `pdb`)
      # - id: requirements-txt-fixer    # Sorts and removes duplicates in requirements.txt files
      # - id: double-quote-string-fixer # Converts single quotes to double quotes in strings
      # - id: name-tests-test # Ensures test files, classes, and functions are named starting with 'test'


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [
          # "--fix",
          # "--exit-non-zero-on-fix",  # CI fails if code was auto-fixed

          "--select=ANN",
          "--select=T20",

          "--ignore=ANN002",
          "--ignore=ANN003",
          "--ignore=Q000",
          "--ignore=Q001",
          "--ignore=Q002",
          "--ignore=BLE001",
          "--ignore=EM102",
          "--ignore=B904",
        ]


  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # or latest stable version
    hooks:
      - id: flake8
        args:
          - --select=E302,E303,E305  # blank lines
        types: [ python ]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [
          "--strict",  # Enables all recommended static checks (strong typing discipline)
          "--ignore-missing-imports",  # Prevents errors for third-party packages without type hints
          # "--no-strict-optional", # Uncomment to allow implicit Optional[...] types (not recommended)
        ]
        additional_dependencies: [
          'types-beautifulsoup4',       # Type stubs for BeautifulSoup4
          'types-requests',             # Type stubs for `requests`
          'types-setuptools',           # Type stubs for `setuptools`
          'types-urllib3',              # Type stubs for `urllib3`
          'types-cachetools',           # Type stubs for `cachetools`
          'atlassian-python-api',       # Actual package
          'beautifulsoup4',             # Required for actual usage along with type stubs
          'httpx',                      # HTTP client library
          'python-dotenv',              # Loads environment variables from `.env` files
          'markdownify',                # HTML → Markdown conversion
          'python-dateutil',            # Enhanced date/time parsing
          'types-python-dateutil',      # Type stubs for `dateutil`
        ]


  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        name: pylint
        args:
          - "--rcfile=code_quality_config/.pylintrc"
          - "--init-hook=import sys; sys.path.insert(0, 'src')"  # adjust a path
          - "--enable-all-extentions"
        additional_dependencies: [
          "pylint-django",  # Optional plugins
          "pylint-flask",  # Optional plugins
        ]
