on:
  workflow_dispatch:
    inputs:
      jira_key:
        description: 'Jira ticket key'
        required: true
      sha:
        description: 'Commit SHA for PR status check'
        required: false

jobs:
  jira-ci:
    name: "${{ inputs.jira_key }} test case"
    runs-on: ubuntu-latest
    steps:
      - name: Set pending status
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ inputs.sha }}',
              state: 'pending',
              context: 'jira-check',
              description: 'Waiting for Jira status...'
            });

      - name: Check Jira status
        run: |
          status="To Do"  # mock
          [[ "$status" == "Done" ]] && echo "done=true" >> $GITHUB_ENV || echo "done=false" >> $GITHUB_ENV

      - name: Set final status (success/failure)
        uses: actions/github-script@v7
        with:
          script: |
            const state = process.env.done === 'true' ? 'success' : 'failure';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ inputs.sha }}',
              state,
              context: 'jira-check',
              description: state === 'success' ? 'Jira ticket is Done ✅' : 'Jira ticket not Done ❌'
            });
