name: Jira CI with PR Check
on:
  workflow_dispatch:
    inputs:
      jira_key:
        description: 'Jira ticket key'
        required: true
      sha:
        description: 'Commit SHA for PR status check'
        required: true
jobs:
  jira-ci:
    name: Jira Check for ${{ inputs.jira_key }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      issues: write
    env:
      JIRA_KEY: ${{ inputs.jira_key }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
    steps:
      - name: Create Check Run
        id: create-check
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: `Jira Check – ${{ inputs.jira_key }}`,
              head_sha: '${{ inputs.sha }}',
              status: 'in_progress',
              started_at: new Date().toISOString(),
              details_url: `https://${{ secrets.JIRA_DOMAIN }}/browse/${{ inputs.jira_key }}`,
              external_id: '${{ inputs.jira_key }}'
            });
            core.setOutput('check_run_id', response.data.id);
      - name: Wait for Jira to be DONE
        id: jira-wait
        run: |
          jira_url="https://${JIRA_DOMAIN}/rest/api/3/issue/${JIRA_KEY}"
          auth_header="Authorization: Basic $(echo -n "${JIRA_EMAIL}:${JIRA_TOKEN}" | base64)"
          for ((i=1;i<=60;i++)); do
            status=$(curl -s -H "Accept: application/json" -H "${auth_header}" "${jira_url}" | jq -r '.fields.status.name')
            echo "Status: $status"
            if [[ "$status" == "Done" ]]; then
              echo "done=true" >> $GITHUB_OUTPUT
              exit 0
            fi
            sleep 30
          done
          echo "done=false" >> $GITHUB_OUTPUT
          exit 1
      - name: Finalize Check Run
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = "${{ steps.jira-wait.outputs.done }}" === "true" ? "success" : "failure";
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: Number("${{ steps.create-check.outputs.check_run_id }}"),
              completed_at: new Date().toISOString(),
              conclusion,
              details_url: `https://${{ secrets.JIRA_DOMAIN }}/browse/${{ inputs.jira_key }}`,
              output: {
                title: 'Jira Status Check',
                summary: conclusion === "success"
                  ? 'Jira ticket is Done ✅'
                  : 'Jira ticket is NOT Done ❌',
                text: `Checked Jira status for ${{ inputs.jira_key }}\n\n[View Jira Ticket](https://${{ secrets.JIRA_DOMAIN }}/browse/${{ inputs.jira_key }})`
              }
            });
