name: Publish to PyPI

on:
  push:
#    branches:
#      - main
    tags:
      - 'v*'  # Triggers only if you push a tag like v1.0.0

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: pwd
        run: pwd

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify installed packages
        run: |
          pip list

      - name: Install Build dependencies
        run: python -m pip install build twine

      - name: List directory contents
        run: |
          pwd
          ls -la

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  deploy:
    name: Upload release to PyPI
    needs: build-and-publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/strands-agents
    permissions:
      id-token: write  # Required for PyPI Trusted Publisher
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
