name: Pytest by Marker

on:
  workflow_dispatch:
    inputs:
      marker:
        description: 'Pytest marker to run (e.g. slow, integration)'
        required: true

jobs:
  pytest-marker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with marker
        run: |
          echo "Running pytest with marker: ${{ inputs.marker }}"
          pytest -m "${{ inputs.marker }}" --disable-warnings -q
