name: Pytest by Marker

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pytest-marker:
    name: "pytest marker: ${{ github.event.pull_request.head.ref }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set commit status to pending
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'pending',
              description: 'Running pytest marker',
              context: 'pytest-marker'
            });

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        id: pytest
        run: |
          pytest -m "YOUR_MARKER_HERE" --maxfail=1 --disable-warnings -q

      - name: Set commit status to success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              description: 'Pytest marker passed',
              context: 'pytest-marker'
            });

      - name: Set commit status to failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'failure',
              description: 'Pytest marker failed',
              context: 'pytest-marker'
            });
