name: Pytest by Marker

on:
  workflow_dispatch:
    inputs:
      marker:
        description: 'Pytest marker to run (e.g. slow, integration)'
        required: true
      sha:
        description: 'Commit SHA for status check'
        required: false

permissions:
  contents: read
  statuses: write
  pull-requests: read

jobs:
  pytest-marker:
    name: "${{ inputs.marker }} pytest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: get-sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Set pending status
        uses: actions/github-script@v7
        with:
          script: |
            const sha = '${{ inputs.sha }}' || '${{ steps.get-sha.outputs.sha }}';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'pending',
              description: 'Running pytest marker: ${{ inputs.marker }}',
              context: 'pytest-marker/${{ inputs.marker }}',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with marker
        run: pytest --mypy -m "${{ inputs.marker }}" --maxfail=1 --disable-warnings -q

      - name: Set final status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const sha = '${{ inputs.sha }}' || '${{ steps.get-sha.outputs.sha }}';
            const state = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            const description = `Pytest marker ${{ inputs.marker }} ${state === 'success' ? 'passed' : 'failed'}`;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state,
              description,
              context: 'pytest-marker/${{ inputs.marker }}',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
